--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KingOfTurkey38/Vaults38
build-by-default: true
branches:
- main
projects:
  Vaults38:
    path: ""
    libs:
      - src: sof3/await-generator/await-generator
        version: ^3.1.0
      - src: sof3/await-std/await-std
        version: ^0.2.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3.2
        branch: "4.0"
...
