---
# The name of the vault's inventory
# {PLAYER} -> The player name
# {NUMBER} -> The vault number
inventory-name: "{PLAYER} #{NUMBER}"
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: host
    # Avoid using the "root" user for security reasons.
    username: username
    password: "password"
    schema: schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1
...
